const fs = require("fs");
const path = require("path");

const OUTPUT_PATH = path.join(
  __dirname,
  "..",
  "lib",
  "titles",
  "titles_ja_1000_universal.ts"
);

const SEED = Number(process.env.OSIKATU_TITLES_SEED ?? "20260202");

const ADJECTIVES = [
  "きらめく",
  "静かな",
  "小さな",
  "やさしい",
  "まっすぐな",
  "確かな",
  "あたたかな",
  "しなやかな",
  "穏やかな",
  "透明な",
  "澄んだ",
  "凛とした",
  "淡い",
  "深い",
  "軽やかな",
  "落ち着いた",
  "誠実な",
  "丁寧な",
  "真剣な",
  "勇気ある",
  "輝く",
  "優雅な",
  "柔らかな",
  "優しい",
  "爽やかな",
  "真面目な",
  "揺るがない",
  "瑞々しい",
  "華やかな",
  "新しい",
  "愛しい",
  "尊い",
  "まぶしい",
  "頼もしい",
  "朗らかな",
  "素直な",
  "夢見る",
  "希望の",
  "絆の",
  "誇りの",
  "笑顔の",
  "光る",
  "静謐な",
  "ひたむきな",
  "細やかな",
  "くっきりとした",
  "芯のある",
  "進む",
  "進化する",
  "支える",
];

const NOUNS = [
  "一歩",
  "情熱",
  "工夫",
  "追い風",
  "積み重ね",
  "達人",
  "まなざし",
  "集中",
  "探究者",
  "光",
  "言葉",
  "音",
  "整え上手",
  "応援団",
  "発見",
  "軌跡",
  "手帳",
  "リズム",
  "約束",
  "覚悟",
  "支柱",
  "情景",
  "心",
  "輪",
  "手ほどき",
  "芽生え",
  "糸口",
  "きっかけ",
  "まほう",
  "光彩",
  "しるし",
  "誓い",
  "旅路",
  "見守り",
  "贈り物",
  "合図",
  "記録",
  "メモ",
  "チューニング",
  "明日",
  "応援",
  "支え",
  "晴れ間",
  "余韻",
  "勇気",
  "余白",
  "ときめき",
  "ひかり",
  "信念",
  "共鳴",
];

const TAG_GROUPS = [
  ["health", "selfcare"],
  ["organize", "cleanup"],
  ["record", "writing"],
  ["music", "watch"],
  ["money", "record"],
  ["study", "memory"],
  ["creative", "joy"],
  ["social", "joy"],
  ["home", "care"],
  ["selfcare", "joy"],
];

const DOMAIN_TAGS = ["domain:daily", "domain:life", "domain:oshi", "domain:balance"];

const RARITY_COUNTS = {
  legendary: 5,
  epic: 25,
  rare: 150,
  common: 820,
};

const createRng = (seed) => {
  let state = seed || 1;
  return () => {
    state ^= state << 13;
    state ^= state >>> 17;
    state ^= state << 5;
    return (state >>> 0) / 4294967296;
  };
};

const shuffle = (items, rng) => {
  const array = [...items];
  for (let i = array.length - 1; i > 0; i -= 1) {
    const j = Math.floor(rng() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
  return array;
};

const buildTitles = () => {
  const titles = [];
  const seen = new Set();
  const rng = createRng(SEED);

  for (const adjective of ADJECTIVES) {
    for (const noun of NOUNS) {
      const title = `${adjective}${noun}`;
      if (seen.has(title)) continue;
      seen.add(title);
      titles.push(title);
      if (titles.length >= 1000) break;
    }
    if (titles.length >= 1000) break;
  }

  if (titles.length < 1000) {
    let idx = 0;
    while (titles.length < 1000) {
      const title = `今日の${NOUNS[idx % NOUNS.length]}${idx + 1}`;
      if (!seen.has(title)) {
        seen.add(title);
        titles.push(title);
      }
      idx += 1;
    }
  }

  const rarities = [
    ...Array(RARITY_COUNTS.legendary).fill("legendary"),
    ...Array(RARITY_COUNTS.epic).fill("epic"),
    ...Array(RARITY_COUNTS.rare).fill("rare"),
    ...Array(RARITY_COUNTS.common).fill("common"),
  ];
  const rarityPool = shuffle(rarities, rng);

  return titles.map((title, index) => {
    const group = TAG_GROUPS[index % TAG_GROUPS.length];
    const extraGroup = TAG_GROUPS[(index + 3) % TAG_GROUPS.length];
    const tags = new Set([...group, ...extraGroup.slice(0, 1)]);
    if (index % 3 === 0) {
      tags.add(DOMAIN_TAGS[index % DOMAIN_TAGS.length]);
    }
    const rarity = rarityPool[index] ?? "common";
    const id = `t${String(index + 1).padStart(4, "0")}`;
    return {
      id,
      title,
      tags: Array.from(tags),
      rarity,
    };
  });
};

const titles = buildTitles();

const lines = [];
lines.push("export type TitleRarity = \"common\" | \"rare\" | \"epic\" | \"legendary\";");
lines.push("");
lines.push("export type TitleEntry = {");
lines.push("  id: string;");
lines.push("  title: string;");
lines.push("  tags: string[];");
lines.push("  rarity: TitleRarity;");
lines.push("};");
lines.push("");
lines.push("// Auto-generated by tools/generate-titles.cjs. Keep UTF-8 (no BOM).");
lines.push("export const TITLES_JA_1000_UNIVERSAL: TitleEntry[] = [");
for (const entry of titles) {
  lines.push(
    `  { id: \"${entry.id}\", title: \"${entry.title}\", tags: ${JSON.stringify(
      entry.tags
    )}, rarity: \"${entry.rarity}\" },`
  );
}
lines.push("];");
lines.push("");

fs.writeFileSync(OUTPUT_PATH, lines.join("\n"), { encoding: "utf8" });
console.log(`Generated ${titles.length} titles -> ${OUTPUT_PATH}`);
