<?php

declare(strict_types=1);

return [
    'cost' => 100,

    // Weight-based prize pools. Keep this config-only for MVP so it works with config cache.
    'pools' => [
        'default' => [
            // Keep IDs aligned with frontend-known ThemeId / FrameId to reflect immediately.
            ['itemType' => 'frame', 'itemKey' => 'polaroid_elegant', 'rarity' => 'R', 'weight' => 55],
            ['itemType' => 'frame', 'itemKey' => 'polaroid_pop', 'rarity' => 'R', 'weight' => 25],
            ['itemType' => 'theme', 'itemKey' => 'midnight', 'rarity' => 'SR', 'weight' => 12],
            ['itemType' => 'theme', 'itemKey' => 'neon', 'rarity' => 'SSR', 'weight' => 7],
            ['itemType' => 'frame', 'itemKey' => 'festival_holo', 'rarity' => 'UR', 'weight' => 1],
        ],
    ],

    'circle_cost' => 100,

    'circle_pools' => [
        'global' => [
            ['itemType' => 'frame', 'itemKey' => 'frame_pop_01', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_pop_02', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_pop_03', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_pop_04', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_pop_05', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_pop_06', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_pop_07', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_pop_08', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_pop_09', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_pop_10', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_dark_01', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_dark_02', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_dark_03', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_dark_04', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_dark_05', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_dark_06', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_dark_07', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_dark_08', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_dark_09', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_dark_10', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_min_01', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_min_02', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_min_03', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_min_04', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_min_05', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_min_06', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_min_07', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_min_08', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_min_09', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_min_10', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_glow_01', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_glow_02', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_glow_03', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_glow_04', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_glow_05', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_glow_06', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_glow_07', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_glow_08', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_glow_09', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'frame', 'itemKey' => 'frame_glow_10', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'theme', 'itemKey' => 'theme_pop_01', 'rarity' => 'SR', 'weight' => 6],
            ['itemType' => 'theme', 'itemKey' => 'theme_pop_02', 'rarity' => 'SR', 'weight' => 6],
            ['itemType' => 'theme', 'itemKey' => 'theme_pop_03', 'rarity' => 'SR', 'weight' => 6],
            ['itemType' => 'theme', 'itemKey' => 'theme_pop_04', 'rarity' => 'SR', 'weight' => 6],
            ['itemType' => 'theme', 'itemKey' => 'theme_pop_05', 'rarity' => 'SR', 'weight' => 6],
            ['itemType' => 'theme', 'itemKey' => 'theme_dark_01', 'rarity' => 'SR', 'weight' => 6],
            ['itemType' => 'theme', 'itemKey' => 'theme_dark_02', 'rarity' => 'SR', 'weight' => 6],
            ['itemType' => 'theme', 'itemKey' => 'theme_dark_03', 'rarity' => 'SR', 'weight' => 6],
            ['itemType' => 'theme', 'itemKey' => 'theme_dark_04', 'rarity' => 'SR', 'weight' => 6],
            ['itemType' => 'theme', 'itemKey' => 'theme_dark_05', 'rarity' => 'SR', 'weight' => 6],
            ['itemType' => 'theme', 'itemKey' => 'theme_neutral_01', 'rarity' => 'SR', 'weight' => 6],
            ['itemType' => 'theme', 'itemKey' => 'theme_neutral_02', 'rarity' => 'SR', 'weight' => 6],
            ['itemType' => 'theme', 'itemKey' => 'theme_neutral_03', 'rarity' => 'SR', 'weight' => 6],
            ['itemType' => 'theme', 'itemKey' => 'theme_neutral_04', 'rarity' => 'SR', 'weight' => 6],
            ['itemType' => 'theme', 'itemKey' => 'theme_neutral_05', 'rarity' => 'SR', 'weight' => 6],
            ['itemType' => 'title', 'itemKey' => 'title_rare_01', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'title', 'itemKey' => 'title_rare_02', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'title', 'itemKey' => 'title_rare_03', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'title', 'itemKey' => 'title_rare_04', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'title', 'itemKey' => 'title_rare_05', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'title', 'itemKey' => 'title_rare_06', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'title', 'itemKey' => 'title_rare_07', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'title', 'itemKey' => 'title_rare_08', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'title', 'itemKey' => 'title_rare_09', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'title', 'itemKey' => 'title_rare_10', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'title', 'itemKey' => 'title_rare_11', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'title', 'itemKey' => 'title_rare_12', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'title', 'itemKey' => 'title_rare_13', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'title', 'itemKey' => 'title_rare_14', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'title', 'itemKey' => 'title_rare_15', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'title', 'itemKey' => 'title_rare_16', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'title', 'itemKey' => 'title_rare_17', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'title', 'itemKey' => 'title_rare_18', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'title', 'itemKey' => 'title_rare_19', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'title', 'itemKey' => 'title_rare_20', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'title', 'itemKey' => 'title_epic_01', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'title', 'itemKey' => 'title_epic_02', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'title', 'itemKey' => 'title_epic_03', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'title', 'itemKey' => 'title_epic_04', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'title', 'itemKey' => 'title_epic_05', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'title', 'itemKey' => 'title_epic_06', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'title', 'itemKey' => 'title_epic_07', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'title', 'itemKey' => 'title_epic_08', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'title', 'itemKey' => 'title_epic_09', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'title', 'itemKey' => 'title_epic_10', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'title', 'itemKey' => 'title_epic_11', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'title', 'itemKey' => 'title_epic_12', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'title', 'itemKey' => 'title_epic_13', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'title', 'itemKey' => 'title_epic_14', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'title', 'itemKey' => 'title_epic_15', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'title', 'itemKey' => 'title_legendary_01', 'rarity' => 'SSR', 'weight' => 2],
            ['itemType' => 'title', 'itemKey' => 'title_legendary_02', 'rarity' => 'SSR', 'weight' => 2],
            ['itemType' => 'title', 'itemKey' => 'title_legendary_03', 'rarity' => 'SSR', 'weight' => 2],
            ['itemType' => 'title', 'itemKey' => 'title_legendary_04', 'rarity' => 'SSR', 'weight' => 2],
            ['itemType' => 'title', 'itemKey' => 'title_legendary_05', 'rarity' => 'SSR', 'weight' => 2],
            ['itemType' => 'title', 'itemKey' => 'title_legendary_06', 'rarity' => 'SSR', 'weight' => 2],
            ['itemType' => 'title', 'itemKey' => 'title_legendary_07', 'rarity' => 'SSR', 'weight' => 2],
            ['itemType' => 'title', 'itemKey' => 'title_legendary_08', 'rarity' => 'SSR', 'weight' => 2],
            ['itemType' => 'title', 'itemKey' => 'title_legendary_09', 'rarity' => 'SSR', 'weight' => 2],
            ['itemType' => 'title', 'itemKey' => 'title_legendary_10', 'rarity' => 'SSR', 'weight' => 2],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_rare_01', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_rare_02', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_rare_03', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_rare_04', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_rare_05', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_rare_06', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_rare_07', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_rare_08', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_rare_09', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_rare_10', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_epic_01', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_epic_02', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_epic_03', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_epic_04', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_epic_05', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_epic_06', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_epic_07', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_epic_08', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_legendary_01', 'rarity' => 'SSR', 'weight' => 2],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_legendary_02', 'rarity' => 'SSR', 'weight' => 2],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_legendary_03', 'rarity' => 'SSR', 'weight' => 2],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_legendary_04', 'rarity' => 'SSR', 'weight' => 2],
            ['itemType' => 'nameplate', 'itemKey' => 'nameplate_legendary_05', 'rarity' => 'SSR', 'weight' => 2],
            ['itemType' => 'entrance', 'itemKey' => 'entrance_rare_01', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'entrance', 'itemKey' => 'entrance_rare_02', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'entrance', 'itemKey' => 'entrance_rare_03', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'entrance', 'itemKey' => 'entrance_rare_04', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'entrance', 'itemKey' => 'entrance_rare_05', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'entrance', 'itemKey' => 'entrance_rare_06', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'entrance', 'itemKey' => 'entrance_rare_07', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'entrance', 'itemKey' => 'entrance_rare_08', 'rarity' => 'R', 'weight' => 8],
            ['itemType' => 'entrance', 'itemKey' => 'entrance_epic_01', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'entrance', 'itemKey' => 'entrance_epic_02', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'entrance', 'itemKey' => 'entrance_epic_03', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'entrance', 'itemKey' => 'entrance_epic_04', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'entrance', 'itemKey' => 'entrance_epic_05', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'entrance', 'itemKey' => 'entrance_epic_06', 'rarity' => 'SR', 'weight' => 4],
            ['itemType' => 'entrance', 'itemKey' => 'entrance_legendary_01', 'rarity' => 'SSR', 'weight' => 2],
            ['itemType' => 'entrance', 'itemKey' => 'entrance_legendary_02', 'rarity' => 'SSR', 'weight' => 2],
            ['itemType' => 'entrance', 'itemKey' => 'entrance_legendary_03', 'rarity' => 'SSR', 'weight' => 2],
            ['itemType' => 'entrance', 'itemKey' => 'entrance_legendary_04', 'rarity' => 'SSR', 'weight' => 2],
            ['itemType' => 'reactpack', 'itemKey' => 'reactpack_01', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'reactpack', 'itemKey' => 'reactpack_02', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'reactpack', 'itemKey' => 'reactpack_03', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'reactpack', 'itemKey' => 'reactpack_04', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'reactpack', 'itemKey' => 'reactpack_05', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'reactpack', 'itemKey' => 'reactpack_06', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'reactpack', 'itemKey' => 'reactpack_07', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'reactpack', 'itemKey' => 'reactpack_08', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'reactpack', 'itemKey' => 'reactpack_09', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'reactpack', 'itemKey' => 'reactpack_10', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'stamp', 'itemKey' => 'stamp_pack_01', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'stamp', 'itemKey' => 'stamp_pack_02', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'stamp', 'itemKey' => 'stamp_pack_03', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'stamp', 'itemKey' => 'stamp_pack_04', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'stamp', 'itemKey' => 'stamp_pack_05', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'stamp', 'itemKey' => 'stamp_pack_06', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'stamp', 'itemKey' => 'stamp_pack_07', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'stamp', 'itemKey' => 'stamp_pack_08', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'stamp', 'itemKey' => 'stamp_pack_09', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'stamp', 'itemKey' => 'stamp_pack_10', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'stamp', 'itemKey' => 'stamp_pack_11', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'stamp', 'itemKey' => 'stamp_pack_12', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'stamp', 'itemKey' => 'stamp_pack_13', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'stamp', 'itemKey' => 'stamp_pack_14', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'stamp', 'itemKey' => 'stamp_pack_15', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'stamp', 'itemKey' => 'stamp_pack_16', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'stamp', 'itemKey' => 'stamp_pack_17', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'stamp', 'itemKey' => 'stamp_pack_18', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'stamp', 'itemKey' => 'stamp_pack_19', 'rarity' => 'R', 'weight' => 10],
            ['itemType' => 'stamp', 'itemKey' => 'stamp_pack_20', 'rarity' => 'R', 'weight' => 10],
        ],
    ],
];
