import type {
  DeadlineItem,
  FeedPost,
  LogPost,
  MoneySnapshot,
  MoneyTransaction,
  Oshi,
  QuickAction,
  ScheduleItem,
  SummaryChip,
  SupplyItem,
  TicketStep,
} from "@/lib/uiTypes";

export const oshis: Oshi[] = [
  {
    id: "sora",
    name: "蒼木ソラ",
    profile: {
      nickname: "ソラちゃん",
      birthday: "2000-02-02",
      height_cm: 160,
      weight_kg: null,
      blood_type: "A",
      accent_color: "343 82% 60%",
      origin: "東京",
      role: "きらめき担当",
      charm_point: "笑顔",
      quote: "今日も推し活でキラッと。",
      hobbies: ["カフェ巡り", "写真"],
      likes: ["キラキラ", "音楽"],
      dislikes: ["早起き"],
      skills: ["歌", "ダンス"],
      favorite_foods: ["ストロベリーラテ", "マカロン"],
      weak_points: ["寒さ"],
      supply_tags: ["ライブ", "配信", "グッズ"],
      anniversaries: [],
      links: [],
      custom_fields: [],
      memo: "王道アイドル系で元気をくれる。",
      image_url: null,
      image_base64: null,
      updated_at: null,
    },
  },
  {
    id: "mina",
    name: "伊藤ミナ",
    profile: {
      nickname: "ミナ",
      birthday: "2001-05-12",
      height_cm: 158,
      weight_kg: null,
      blood_type: "O",
      accent_color: "200 80% 60%",
      origin: "横浜",
      role: "透明感ボイス",
      charm_point: "透明感",
      quote: "ふわっと寄り添う声。",
      hobbies: ["アート", "映画"],
      likes: ["夜景", "香水"],
      dislikes: ["暑さ"],
      skills: ["トーク", "ハンドメイド"],
      favorite_foods: ["ミルクティー", "チーズケーキ"],
      weak_points: ["早起き"],
      supply_tags: ["配信", "コラボ"],
      anniversaries: [],
      links: [],
      custom_fields: [],
      memo: "夜に聴きたい癒し枠。",
      image_url: null,
      image_base64: null,
      updated_at: null,
    },
  },
  {
    id: "rei",
    name: "加藤レイ",
    profile: {
      nickname: "レイ",
      birthday: "1999-10-20",
      height_cm: 165,
      weight_kg: null,
      blood_type: "B",
      accent_color: "260 75% 75%",
      origin: "大阪",
      role: "クール担当",
      charm_point: "低音ボイス",
      quote: "静かに熱く。",
      hobbies: ["ゲーム", "読書"],
      likes: ["ブラックコーヒー", "夜更かし"],
      dislikes: ["にぎやかすぎる場所"],
      skills: ["ラップ", "MC"],
      favorite_foods: ["カヌレ", "ビターチョコ"],
      weak_points: ["甘いもの"],
      supply_tags: ["ライブ", "コラボ"],
      anniversaries: [],
      links: [],
      custom_fields: [],
      memo: "クールなパフォーマンスが魅力。",
      image_url: null,
      image_base64: null,
      updated_at: null,
    },
  },
];

export const todaySummary: SummaryChip[] = [
  { id: "next", label: "次の予定まで", value: "2日", tone: "accent" },
  { id: "supply", label: "今日の供給", value: "4件", tone: "muted" },
  { id: "mood", label: "気分", value: "最高", tone: "muted" },
];

export const quickActions: QuickAction[] = [
  {
    id: "log",
    label: "ログする",
    title: "ログする",
    description: "今日のときめきを残そう",
    placeholder: "今日の一番のトキメキは？",
  },
  {
    id: "schedule",
    label: "予定追加",
    title: "予定追加",
    description: "リマインドを先に作る",
    placeholder: "次に控えている予定は？",
  },
  {
    id: "money",
    label: "支出追加",
    title: "支出追加",
    description: "支出をざっくり記録",
    placeholder: "いくら使った？",
  },
  {
    id: "supply",
    label: "供給メモ",
    title: "供給メモ",
    description: "見逃さないメモ",
    placeholder: "今日の供給まとめ",
  },
];

export const supplies: SupplyItem[] = [
  {
    id: "sup-1",
    title: "ホールツアー抽選締切",
    category: "ライブ",
    date: "今日 23:59",
    period: "today",
    priority: "high",
    badge: "締切",
    note: "第2希望まで入力",
  },
  {
    id: "sup-2",
    title: "新作グッズ 受注開始",
    category: "グッズ",
    date: "今日 20:00",
    period: "today",
    priority: "normal",
    badge: "販売",
  },
  {
    id: "sup-3",
    title: "歌枠配信",
    category: "配信",
    date: "今日 22:00",
    period: "today",
    priority: "normal",
  },
  {
    id: "sup-4",
    title: "コラボ告知",
    category: "コラボ",
    date: "明日 19:00",
    period: "today",
    priority: "normal",
  },
  {
    id: "sup-5",
    title: "アリーナ先行抽選",
    category: "ライブ",
    date: "1/31 12:00",
    period: "week",
    priority: "high",
    badge: "抽選",
  },
  {
    id: "sup-6",
    title: "バースデーグッズ受注",
    category: "グッズ",
    date: "2/02 23:59",
    period: "week",
    priority: "normal",
  },
  {
    id: "sup-7",
    title: "朝活配信",
    category: "配信",
    date: "2/03 07:00",
    period: "week",
    priority: "normal",
  },
  {
    id: "sup-8",
    title: "コラボカフェ予約開始",
    category: "コラボ",
    date: "2/04 10:00",
    period: "week",
    priority: "high",
    badge: "先着",
  },
];

export const deadlines: DeadlineItem[] = [
  {
    id: "dead-1",
    title: "グッズ予約締切",
    date: "1/31 23:59",
    remain: "あと2日",
    level: "urgent",
  },
  {
    id: "dead-2",
    title: "抽選入金期限",
    date: "2/01 15:00",
    remain: "あと3日",
    level: "urgent",
  },
  {
    id: "dead-3",
    title: "配信アーカイブ期限",
    date: "2/03 23:59",
    remain: "あと5日",
    level: "normal",
  },
  {
    id: "dead-4",
    title: "ファンレター締切",
    date: "2/05 20:00",
    remain: "あと7日",
    level: "normal",
  },
];

export const moneySnapshot: MoneySnapshot = {
  budget: 24000,
  spent: 14200,
  remaining: 9800,
  categories: [
    { id: "cat-1", label: "グッズ", amount: 5200 },
    { id: "cat-2", label: "現場", amount: 5800 },
    { id: "cat-3", label: "遠征", amount: 2100 },
    { id: "cat-4", label: "サブスク", amount: 1100 },
  ],
};

export const moneyTransactions: MoneyTransaction[] = [
  { id: "txn-1", title: "ホロカードセット", date: "1/27", amount: 2400, category: "グッズ" },
  { id: "txn-2", title: "ライブチケット", date: "1/25", amount: 5800, category: "現場" },
  { id: "txn-3", title: "ファンカフェドリンク", date: "1/23", amount: 900, category: "現場" },
  { id: "txn-4", title: "推し色ネイル", date: "1/21", amount: 2000, category: "グッズ" },
];

export const miniFeed: FeedPost[] = [
  {
    id: "feed-1",
    name: "ミカ",
    handle: "@mika",
    time: "2時間前",
    content: "神席で泣いた。銀テも取れた…！",
    tags: ["現場", "神席"],
    image: true,
  },
  {
    id: "feed-2",
    name: "ユナ",
    handle: "@yuna",
    time: "3時間前",
    content: "開封の結果…SSR出た！",
    tags: ["開封", "神引き"],
    image: true,
  },
  {
    id: "feed-3",
    name: "レイ",
    handle: "@rei",
    time: "5時間前",
    content: "歌枠が最高に癒しだった。",
    tags: ["配信", "歌枠"],
  },
  {
    id: "feed-4",
    name: "ミナ",
    handle: "@mina",
    time: "6時間前",
    content: "カフェ集合の打ち合わせ完了。",
    tags: ["カフェ", "集合"],
  },
];

export const logTemplates = [
  { id: "live", label: "現場", title: "現場メモ", tags: ["現場", "神席"] },
  { id: "unbox", label: "開封", title: "開封ログ", tags: ["開封", "神引き"] },
  { id: "stream", label: "配信", title: "配信メモ", tags: ["配信", "歌枠"] },
  { id: "review", label: "感想", title: "感想ログ", tags: ["感想", "尊い"] },
];

export const logPosts: LogPost[] = [
  {
    id: "log-1",
    title: "神席だった日",
    body: "目の前でレスもらって震えた。",
    tags: ["現場", "神席"],
    time: "10分前",
    date: "2026-01-28",
    image: true,
  },
  {
    id: "log-2",
    title: "開封結果",
    body: "SSRが出た瞬間に叫んだ。",
    tags: ["開封", "神引き"],
    time: "1時間前",
    date: "2026-01-27",
    image: true,
  },
  {
    id: "log-3",
    title: "歌枠の癒し",
    body: "今日も歌声に救われた。",
    tags: ["配信", "歌枠"],
    time: "3時間前",
  },
  {
    id: "log-4",
    title: "カフェ集合",
    body: "次の現場に向けてみんなで準備。",
    tags: ["集合", "作戦会議"],
    time: "昨日",
  },
];

export const ticketTimeline: TicketStep[] = [
  { id: "step-1", label: "申込", date: "1/20", status: "done" },
  { id: "step-2", label: "締切", date: "1/30", status: "current" },
  { id: "step-3", label: "当落", date: "2/01", status: "upcoming" },
  { id: "step-4", label: "入金", date: "2/03", status: "upcoming" },
  { id: "step-5", label: "発券", date: "2/07", status: "upcoming" },
];

export const scheduleList: ScheduleItem[] = [
  {
    id: "sch-1",
    title: "配信：冬のQ&A",
    date: "1/30 20:00",
    place: "YouTube",
  },
  {
    id: "sch-2",
    title: "コラボ配信",
    date: "2/02 19:30",
    place: "Twitch",
    conflict: true,
  },
  {
    id: "sch-3",
    title: "ファンカフェ集合",
    date: "2/06 15:00",
    place: "渋谷",
  },
];
